# Generated by Django 5.2.3 on 2025-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
