# Generated by Django 5.2.3 on 2025-07-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikemodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlikemodel',
            name='commentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='posts.commentmodel'),
        ),
        migrations.AddField(
            model_name='postlikemodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='posts.hashtagmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='posts.musicmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlikemodel',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.postmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postmodel'),
        ),
        migrations.AddField(
            model_name='replycommentlikemodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replycommentmodel',
            name='commentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='posts.commentmodel'),
        ),
        migrations.AddField(
            model_name='replycommentmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replycommentlikemodel',
            name='reply_commentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_likes', to='posts.replycommentmodel'),
        ),
        migrations.AddField(
            model_name='musicmodel',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='posts.singermodel'),
        ),
    ]
