# Generated by Django 5.2.3 on 2025-08-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='comment_like',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.commentmodel'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='post_like',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.postmodel'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='reply_comment_like',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.replycommentmodel'),
        ),
    ]
