# Generated by Django 5.2.3 on 2025-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_hashtags_alter_postmodel_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='hashtags',
            field=models.ManyToManyField(to='posts.hashtagmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='music',
            field=models.ManyToManyField(to='posts.musicmodel'),
        ),
    ]
