# Generated by Django 5.2.3 on 2025-08-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_notificationmodel_followed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='followed_by',
        ),
    ]
