# Generated by Django 5.2.3 on 2025-08-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_notificationmodel_followed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
