# Generated by Django 5.2.3 on 2025-08-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_notificationmodel_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='is_seen',
            new_name='is_read',
        ),
    ]
