# Generated by Django 5.2.3 on 2025-08-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_is_seen_notificationmodel_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
