# Generated by Django 5.2.3 on 2025-08-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postmodel_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
