# Generated by Django 5.2.3 on 2025-08-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postmodel_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
