# Generated by Django 5.2.3 on 2025-06-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
    ]
